name = "chrome"
name_cn = "Chrome 浏览器"
description = "Google Chrome 网页浏览器"
author = "cyanteam"
contact = "qtof@qq.com"
version = "0.0.0"
language = "native"
architecture = "multi"
package_id = "com.google.chrome"

[config_command]
common = "{install_path}/_CYPASSETS/chrome"
macosarm64 = "open -a 'Google Chrome'"
macosintel = "open -a 'Google Chrome'"
linux64 = "{install_path}/_CYPASSETS/google-chrome-stable"
win64 = "{install_path}/_CYPASSETS/chrome.exe"

[assets]
